"""empty message

Revision ID: 03a1630c18c7
Revises: 54388d22ef2d
Create Date: 2021-03-17 00:36:21.156060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03a1630c18c7'
down_revision = '54388d22ef2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('phone', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'phone')
    # ### end Alembic commands ###
