"""empty message

Revision ID: 7f6136f05c14
Revises: 03a1630c18c7
Create Date: 2021-03-17 05:49:28.132568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f6136f05c14'
down_revision = '03a1630c18c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'address')
    op.drop_column('user_info', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('phone', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('user_info', sa.Column('address', mysql.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
